#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper~Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

virt-install --virt-type kvm --name vyos_cont --ram 1024 \
--cdrom=/vm/vyos-1.1.7-amd64.iso \
--disk path=/vm/vyos_cont.qcow2,size=2,format=qcow2 \
--network bridge=virbr601 \
--network bridge=virbr550 \
--network bridge=virbr551 \
--network bridge=virbr552 \
--network bridge=virbr515 \
--network network=default \
--network bridge=virbr3001 \
--graphics none \
--os-type=linux --os-variant=debian7

