#!/bin/bash

:<<'hopper-stack-notice'

Copyright 2016 Hopper~Stack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

hopper-stack-notice

virt-install --virt-type kvm --name win2k12r2 --ram 4096 \
--cdrom=/vm/windows-2012r2.iso \
--disk path=/vm/win2k12r2.qcow2,size=50,format=qcow2,bus=ide \
--network network=default \
--graphics vnc,listen=0.0.0.0 --noautoconsole \
--os-type=windows --os-variant=win2k12r2

